### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by banduoba** [kerlw/weapp-support-plugin#1]
已在 pycharm 里面安装,请问如何使用呢,貌似没有自动语法提示

**Comment by kerlw** [comment]
pycharm我没试过，pycharm是做python的吧，我是在webstorm里面用的。微信小程序开发主要就是js、wxml（xml）、wxss（css）三种文件，目前三类文件都能够有语法高亮和提示，js会包括wx的api。xml其实是用的基本的html语法，所以wx:if这样的会识别不了，css里面还不能识别rpx为单位，这些以后慢慢完善。
