### ISSUE TITLE
在webstorm上安装了0.1.0的插件，WXML文件不能识别。

### ISSUE THREAD

**Issue by liupeng3425** [kerlw/weapp-support-plugin#2]
在webstorm上安装了0.1.0的插件，WXML文件不能识别，WXSS正常。

**Comment by kerlw** [comment]
我测试过是好的，你说的不能识别是怎么个不能识别法？图标我用了一个带字母‘H’的文件图标，文件内容语法分析是用了HTML的类型语法分析，所以文件内容很多地方会显示有错误，暂时没有时间改进这一块了。前段时间在研究怎么在wxss里面增加rpx单位的支持，对插件的psi这一块有那么一点点理解了，但是这整个体系还是蛮复杂的，至少wxss从css直接继承，想要添加rpx的支持，我是没找到什么简捷可行的方案的。wxml这一块应该要通过扩展点把一些语法分析加进去，主要是wx:if / elif /else，以及{{var}}的支持。后面有时间了我再折腾一下吧。如果有对idea插件开发有经验的大牛愿意在我这个项目基础上做改进，我也是求之不得的。
