### ISSUE TITLE
idea安装后能识别wxss文件，但rpx单位报错

### ISSUE THREAD

**Issue by superxiaobin** [kerlw/weapp-support-plugin#3]
idea安装后能识别wxss文件，但rpx单位报错，格式化代码后，rpx和前面会多个空格，这样css会报错

**Comment by kerlw** [comment]
我在readme里面已经讲过了，css不支持rpx，我探索了很久，最终的结论是没有办法直接通过继承/改写css相关的类来实现对新单位的支持。要实现rpx支持，需要拿css支持的代码来做修改，但是很遗憾这部分不是开源的，我并没有，也没有精力去整，所以，只有保持暂时不支持rpx的状态了。

**Comment by superxiaobin** [comment]
好的

**Comment by zxj5470** [comment]
这个问题得用另外的办法来解决。。。我已经搞定了

**Comment by kerlw** [comment]
> 这个问题得用另外的办法来解决。。。我已经搞定了

哦，厉害厉害～～是否能够分享一下

**Comment by zxj5470** [comment]
就是魔改源码，在plugin.xml 里面添加 lang.formatter 里面复制全套内容，反编译以后修改 CssFormattingModelBuilder 的代码。具体代码在 CssPropertyBlock getSpacing 里面……（说起来比较复杂）

**Comment by kerlw** [comment]
如果是反编译改写的话，我感觉好像有一个非常简单的修改方法，就是在CssSuffixes里面把rpx加入到LENGTH_SUFFIXES里面去，我没去试，不知道 @zxj5470  是否能够代为测试一下
